# Generated by Django 4.1.3 on 2024-04-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARI_CO', models.FloatField()),
                ('ARI_PO', models.FloatField()),
                ('SHIP_TYPE_Category', models.FloatField()),
                ('DIST', models.FloatField()),
                ('BREADTH', models.FloatField()),
                ('BUILT', models.BigIntegerField()),
                ('DEADWEIGHT', models.BigIntegerField()),
                ('DEPTH', models.FloatField()),
                ('DRAUGHT', models.FloatField()),
                ('GT', models.BigIntegerField()),
                ('LENGTH', models.FloatField()),
                ('FLAG', models.FloatField()),
                ('U_WIND', models.FloatField()),
                ('V_WIND', models.FloatField()),
                ('AIR_TEMPERATURE', models.FloatField()),
                ('BN', models.FloatField()),
                ('ATA_LT', models.BigIntegerField()),
                ('PORT_SIZE', models.FloatField()),
                ('CI_HOUR', models.FloatField()),
                ('year', models.BigIntegerField()),
                ('month', models.BigIntegerField()),
                ('day', models.BigIntegerField()),
                ('hour', models.BigIntegerField()),
                ('minute', models.BigIntegerField()),
                ('weekday', models.BigIntegerField()),
            ],
            options={
                'db_table': 'data4',
                'managed': False,
            },
        ),
    ]
